// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ApiV1BudgetsAllGetAllBudgetsData, ApiV1BudgetsAllGetAllBudgetsResponses, ApiV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetData, ApiV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetErrors, ApiV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetResponses, ApiV1BudgetsCreateCreateBudgetData, ApiV1BudgetsCreateCreateBudgetErrors, ApiV1BudgetsCreateCreateBudgetResponses, ApiV1BudgetsNamesGetBudgetsNamesData, ApiV1BudgetsNamesGetBudgetsNamesResponses, ApiV1HealthHealthCheckData, ApiV1HealthHealthCheckResponses, ApiV1TransactionsGetTransactionsData, ApiV1TransactionsGetTransactionsErrors, ApiV1TransactionsGetTransactionsResponses, ApiV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointData, ApiV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointErrors, ApiV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointResponses, ApiV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointData, ApiV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointErrors, ApiV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointResponses, ApiV1TransactionsTransactionIdBreakdownCreateBreakdownData, ApiV1TransactionsTransactionIdBreakdownCreateBreakdownErrors, ApiV1TransactionsTransactionIdBreakdownCreateBreakdownResponses, ApiV1TransactionsTransactionIdBreakdownGetBreakdownData, ApiV1TransactionsTransactionIdBreakdownGetBreakdownErrors, ApiV1TransactionsTransactionIdBreakdownGetBreakdownResponses, ApiV1TransactionsTransactionIdTypeMarkTransactionTypeEndpointData, ApiV1TransactionsTransactionIdTypeMarkTransactionTypeEndpointErrors, ApiV1TransactionsTransactionIdTypeMarkTransactionTypeEndpointResponses, ApiV1TransactionsUpdateUpdateTransactionsData, ApiV1TransactionsUpdateUpdateTransactionsResponses, ApiV1UserTokenUpdateAccessUrlEndpointData, ApiV1UserTokenUpdateAccessUrlEndpointErrors, ApiV1UserTokenUpdateAccessUrlEndpointResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * UpdateAccessUrlEndpoint
 *
 * Auto-generated gateway endpoint for http://localhost:8082/api/v1/user/token
 */
export const apiV1UserTokenUpdateAccessUrlEndpoint = <ThrowOnError extends boolean = false>(options: Options<ApiV1UserTokenUpdateAccessUrlEndpointData, ThrowOnError>) => {
    return (options.client ?? client).put<ApiV1UserTokenUpdateAccessUrlEndpointResponses, ApiV1UserTokenUpdateAccessUrlEndpointErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/finance/v1/user/token',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * CreateBudget
 *
 * Auto-generated gateway endpoint for http://localhost:8082/api/v1/budgets/create
 */
export const apiV1BudgetsCreateCreateBudget = <ThrowOnError extends boolean = false>(options: Options<ApiV1BudgetsCreateCreateBudgetData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiV1BudgetsCreateCreateBudgetResponses, ApiV1BudgetsCreateCreateBudgetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/finance/v1/budgets/create',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * AddTransactionToBudget
 *
 * Auto-generated gateway endpoint for http://localhost:8082/api/v1/budgets/{budget_id}/transactions/{transaction_id}
 */
export const apiV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudget = <ThrowOnError extends boolean = false>(options: Options<ApiV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetResponses, ApiV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/finance/v1/budgets/{budget_id}/transactions/{transaction_id}',
        ...options
    });
};

/**
 * GetAllBudgets
 *
 * Auto-generated gateway endpoint for http://localhost:8082/api/v1/budgets/all
 */
export const apiV1BudgetsAllGetAllBudgets = <ThrowOnError extends boolean = false>(options?: Options<ApiV1BudgetsAllGetAllBudgetsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ApiV1BudgetsAllGetAllBudgetsResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/finance/v1/budgets/all',
        ...options
    });
};

/**
 * GetBudgetsNames
 *
 * Auto-generated gateway endpoint for http://localhost:8082/api/v1/budgets/names
 */
export const apiV1BudgetsNamesGetBudgetsNames = <ThrowOnError extends boolean = false>(options?: Options<ApiV1BudgetsNamesGetBudgetsNamesData, ThrowOnError>) => {
    return (options?.client ?? client).get<ApiV1BudgetsNamesGetBudgetsNamesResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/finance/v1/budgets/names',
        ...options
    });
};

/**
 * GetTransactions
 *
 * Auto-generated gateway endpoint for http://localhost:8082/api/v1/transactions
 */
export const apiV1TransactionsGetTransactions = <ThrowOnError extends boolean = false>(options: Options<ApiV1TransactionsGetTransactionsData, ThrowOnError>) => {
    return (options.client ?? client).get<ApiV1TransactionsGetTransactionsResponses, ApiV1TransactionsGetTransactionsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/finance/v1/transactions',
        ...options
    });
};

/**
 * UpdateTransactions
 *
 * Auto-generated gateway endpoint for http://localhost:8082/api/v1/transactions/update
 */
export const apiV1TransactionsUpdateUpdateTransactions = <ThrowOnError extends boolean = false>(options?: Options<ApiV1TransactionsUpdateUpdateTransactionsData, ThrowOnError>) => {
    return (options?.client ?? client).post<ApiV1TransactionsUpdateUpdateTransactionsResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/finance/v1/transactions/update',
        ...options
    });
};

/**
 * GetBreakdown
 *
 * Auto-generated gateway endpoint for http://localhost:8082/api/v1/transactions/{transaction_id}/breakdown
 */
export const apiV1TransactionsTransactionIdBreakdownGetBreakdown = <ThrowOnError extends boolean = false>(options: Options<ApiV1TransactionsTransactionIdBreakdownGetBreakdownData, ThrowOnError>) => {
    return (options.client ?? client).get<ApiV1TransactionsTransactionIdBreakdownGetBreakdownResponses, ApiV1TransactionsTransactionIdBreakdownGetBreakdownErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/finance/v1/transactions/{transaction_id}/breakdown',
        ...options
    });
};

/**
 * CreateBreakdown
 *
 * Auto-generated gateway endpoint for http://localhost:8082/api/v1/transactions/{transaction_id}/breakdown
 */
export const apiV1TransactionsTransactionIdBreakdownCreateBreakdown = <ThrowOnError extends boolean = false>(options: Options<ApiV1TransactionsTransactionIdBreakdownCreateBreakdownData, ThrowOnError>) => {
    return (options.client ?? client).post<ApiV1TransactionsTransactionIdBreakdownCreateBreakdownResponses, ApiV1TransactionsTransactionIdBreakdownCreateBreakdownErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/finance/v1/transactions/{transaction_id}/breakdown',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * DeleteLineItemEndpoint
 *
 * Auto-generated gateway endpoint for http://localhost:8082/api/v1/transactions/line-items/{line_item_id}
 */
export const apiV1TransactionsLineItemsLineItemIdDeleteLineItemEndpoint = <ThrowOnError extends boolean = false>(options: Options<ApiV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointData, ThrowOnError>) => {
    return (options.client ?? client).delete<ApiV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointResponses, ApiV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/finance/v1/transactions/line-items/{line_item_id}',
        ...options
    });
};

/**
 * UpdateLineItemEndpoint
 *
 * Auto-generated gateway endpoint for http://localhost:8082/api/v1/transactions/line-items/{line_item_id}
 */
export const apiV1TransactionsLineItemsLineItemIdUpdateLineItemEndpoint = <ThrowOnError extends boolean = false>(options: Options<ApiV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointData, ThrowOnError>) => {
    return (options.client ?? client).put<ApiV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointResponses, ApiV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/finance/v1/transactions/line-items/{line_item_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * MarkTransactionTypeEndpoint
 *
 * Auto-generated gateway endpoint for http://localhost:8082/api/v1/transactions/{transaction_id}/type
 */
export const apiV1TransactionsTransactionIdTypeMarkTransactionTypeEndpoint = <ThrowOnError extends boolean = false>(options: Options<ApiV1TransactionsTransactionIdTypeMarkTransactionTypeEndpointData, ThrowOnError>) => {
    return (options.client ?? client).patch<ApiV1TransactionsTransactionIdTypeMarkTransactionTypeEndpointResponses, ApiV1TransactionsTransactionIdTypeMarkTransactionTypeEndpointErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/finance/v1/transactions/{transaction_id}/type',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * HealthCheck
 *
 * Auto-generated gateway endpoint for http://localhost:8082/api/v1/health
 */
export const apiV1HealthHealthCheck = <ThrowOnError extends boolean = false>(options?: Options<ApiV1HealthHealthCheckData, ThrowOnError>) => {
    return (options?.client ?? client).get<ApiV1HealthHealthCheckResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/finance/v1/health',
        ...options
    });
};
