// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * TransactionWithBreakdownResponse
 */
export type TransactionWithBreakdownResponse = {
    id: number;
    transaction_id: string;
    amount: number;
    description?: string | null;
    payee?: string | null;
    transacted_at: string;
    is_split: boolean;
    budget_id?: number | null;
    line_items?: Array<TransactionLineItemResponse>;
};

/**
 * TransactionLineItemResponse
 */
export type TransactionLineItemResponse = {
    id: number;
    description: string;
    amount: number;
    quantity?: number | null;
    unit_price?: number | null;
    category?: string | null;
    budget_id?: number | null;
    notes?: string | null;
};

/**
 * TokenRequest
 */
export type TokenRequest = {
    token: string;
};

/**
 * SimpleFinAccountSchema
 */
export type SimpleFinAccountSchema = {
    id: number;
    account_id: string;
    name: string;
    currency: string;
    balance: number;
    available_balance?: number | null;
    balance_date: string;
    possible_error: boolean;
    extra?: {
        [key: string]: unknown;
    } | null;
    updated_at: string;
};

/**
 * IncomeBudgetResponse
 */
export type IncomeBudgetResponse = {
    id: number;
    user_id: number;
    enable: boolean;
    deleted: boolean;
    fixed: boolean;
    expected_amount?: number | null;
    min?: number | null;
    max?: number | null;
    name: string;
    transaction_sum: number;
    amount_after_transactions: number;
};

/**
 * GetTransactionsListResponse
 */
export type GetTransactionsListResponse = {
    transactions: Array<GetTransactionResponse>;
};

/**
 * BudgetSchema
 */
export type BudgetSchema = {
    id: number;
    name: string;
};

/**
 * GetTransactionResponse
 */
export type GetTransactionResponse = {
    id: number;
    transaction_id: string;
    posted?: string | null;
    amount: number;
    description?: string | null;
    payee?: string | null;
    memo?: string | null;
    transacted_at: string;
    pending: boolean;
    extra?: {
        [key: string]: unknown;
    } | null;
    updated_at: string;
    account: SimpleFinAccountSchema;
    budget?: BudgetSchema | null;
    is_split: boolean;
};

/**
 * FundBudgetResponse
 */
export type FundBudgetResponse = {
    id: number;
    user_id: number;
    enable: boolean;
    deleted: boolean;
    priority?: number | null;
    increment?: number | null;
    current_amount?: number | null;
    max?: number | null;
    name: string;
    transaction_sum: number;
    amount_after_transactions: number;
};

/**
 * FlexibleBudgetResponse
 */
export type FlexibleBudgetResponse = {
    id: number;
    user_id: number;
    enable: boolean;
    deleted: boolean;
    fixed: boolean;
    expected_amount?: number | null;
    min?: number | null;
    max?: number | null;
    name: string;
    transaction_sum: number;
    amount_after_transactions: number;
};

/**
 * ExpenseBudgetResponse
 */
export type ExpenseBudgetResponse = {
    id: number;
    user_id: number;
    enable: boolean;
    deleted: boolean;
    fixed: boolean;
    expected_amount?: number | null;
    min?: number | null;
    max?: number | null;
    name: string;
    transaction_sum: number;
    amount_after_transactions: number;
};

/**
 * CreateLineItemRequest
 */
export type CreateLineItemRequest = {
    description: string;
    amount: number;
    quantity?: number | null;
    unit_price?: number | null;
    category?: string | null;
    budget_id?: number | null;
    notes?: string | null;
};

/**
 * CreateBreakdownRequest
 */
export type CreateBreakdownRequest = {
    transaction_id: number;
    line_items: Array<CreateLineItemRequest>;
};

/**
 * BudgetRequest
 */
export type BudgetRequest = {
    name: string;
    fixed?: boolean;
    flexible?: boolean;
    budget_type: string;
    expected_amount?: number | null;
    min?: number | null;
    max?: number | null;
    priority?: number | null;
    increment?: number | null;
    current_amount?: number | null;
    month: number;
    year: number;
};

/**
 * BudgetNameResponse
 */
export type BudgetNameResponse = {
    name: string;
    id: number;
};

/**
 * AllBudgetsResponse
 */
export type AllBudgetsResponse = {
    incomes?: Array<IncomeBudgetResponse>;
    expenses?: Array<ExpenseBudgetResponse>;
    flexibles?: Array<FlexibleBudgetResponse>;
    funds?: Array<FundBudgetResponse>;
};

export type ApiFinanceV1TransactionsGetTransactionsData = {
    body?: never;
    path?: never;
    query: {
        page: number;
        descending: boolean;
        sort_by: string;
        rows_per_page: number;
    };
    url: '/api/finance/v1/transactions';
};

export type ApiFinanceV1TransactionsGetTransactionsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiFinanceV1TransactionsGetTransactionsError = ApiFinanceV1TransactionsGetTransactionsErrors[keyof ApiFinanceV1TransactionsGetTransactionsErrors];

export type ApiFinanceV1TransactionsGetTransactionsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: GetTransactionsListResponse;
};

export type ApiFinanceV1TransactionsGetTransactionsResponse = ApiFinanceV1TransactionsGetTransactionsResponses[keyof ApiFinanceV1TransactionsGetTransactionsResponses];

export type ApiFinanceV1TransactionsUpdateUpdateTransactionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/finance/v1/transactions/update';
};

export type ApiFinanceV1TransactionsUpdateUpdateTransactionsResponses = {
    /**
     * Document created, URL follows
     */
    201: {
        [key: string]: string;
    };
};

export type ApiFinanceV1TransactionsUpdateUpdateTransactionsResponse = ApiFinanceV1TransactionsUpdateUpdateTransactionsResponses[keyof ApiFinanceV1TransactionsUpdateUpdateTransactionsResponses];

export type ApiFinanceV1TransactionsTransactionIdBreakdownGetBreakdownData = {
    body?: never;
    path: {
        transaction_id: number;
    };
    query?: never;
    url: '/api/finance/v1/transactions/{transaction_id}/breakdown';
};

export type ApiFinanceV1TransactionsTransactionIdBreakdownGetBreakdownErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiFinanceV1TransactionsTransactionIdBreakdownGetBreakdownError = ApiFinanceV1TransactionsTransactionIdBreakdownGetBreakdownErrors[keyof ApiFinanceV1TransactionsTransactionIdBreakdownGetBreakdownErrors];

export type ApiFinanceV1TransactionsTransactionIdBreakdownGetBreakdownResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: TransactionWithBreakdownResponse;
};

export type ApiFinanceV1TransactionsTransactionIdBreakdownGetBreakdownResponse = ApiFinanceV1TransactionsTransactionIdBreakdownGetBreakdownResponses[keyof ApiFinanceV1TransactionsTransactionIdBreakdownGetBreakdownResponses];

export type ApiFinanceV1TransactionsTransactionIdBreakdownCreateBreakdownData = {
    body: CreateBreakdownRequest;
    path: {
        transaction_id: number;
    };
    query?: never;
    url: '/api/finance/v1/transactions/{transaction_id}/breakdown';
};

export type ApiFinanceV1TransactionsTransactionIdBreakdownCreateBreakdownErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiFinanceV1TransactionsTransactionIdBreakdownCreateBreakdownError = ApiFinanceV1TransactionsTransactionIdBreakdownCreateBreakdownErrors[keyof ApiFinanceV1TransactionsTransactionIdBreakdownCreateBreakdownErrors];

export type ApiFinanceV1TransactionsTransactionIdBreakdownCreateBreakdownResponses = {
    /**
     * Document created, URL follows
     */
    201: TransactionWithBreakdownResponse;
};

export type ApiFinanceV1TransactionsTransactionIdBreakdownCreateBreakdownResponse = ApiFinanceV1TransactionsTransactionIdBreakdownCreateBreakdownResponses[keyof ApiFinanceV1TransactionsTransactionIdBreakdownCreateBreakdownResponses];

export type ApiFinanceV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointData = {
    body?: never;
    path: {
        line_item_id: number;
    };
    query?: never;
    url: '/api/finance/v1/transactions/line-items/{line_item_id}';
};

export type ApiFinanceV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiFinanceV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointError = ApiFinanceV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointErrors[keyof ApiFinanceV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointErrors];

export type ApiFinanceV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointResponses = {
    /**
     * Request fulfilled, nothing follows
     */
    204: void;
};

export type ApiFinanceV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointResponse = ApiFinanceV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointResponses[keyof ApiFinanceV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointResponses];

export type ApiFinanceV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointData = {
    body: CreateLineItemRequest;
    path: {
        line_item_id: number;
    };
    query?: never;
    url: '/api/finance/v1/transactions/line-items/{line_item_id}';
};

export type ApiFinanceV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiFinanceV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointError = ApiFinanceV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointErrors[keyof ApiFinanceV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointErrors];

export type ApiFinanceV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: TransactionLineItemResponse;
};

export type ApiFinanceV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointResponse = ApiFinanceV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointResponses[keyof ApiFinanceV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointResponses];

export type ApiFinanceV1BudgetsCreateCreateBudgetData = {
    body: BudgetRequest;
    path?: never;
    query?: never;
    url: '/api/finance/v1/budgets/create';
};

export type ApiFinanceV1BudgetsCreateCreateBudgetErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiFinanceV1BudgetsCreateCreateBudgetError = ApiFinanceV1BudgetsCreateCreateBudgetErrors[keyof ApiFinanceV1BudgetsCreateCreateBudgetErrors];

export type ApiFinanceV1BudgetsCreateCreateBudgetResponses = {
    /**
     * Document created, URL follows
     */
    201: {
        [key: string]: string;
    };
};

export type ApiFinanceV1BudgetsCreateCreateBudgetResponse = ApiFinanceV1BudgetsCreateCreateBudgetResponses[keyof ApiFinanceV1BudgetsCreateCreateBudgetResponses];

export type ApiFinanceV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetData = {
    body?: never;
    path: {
        budget_id: number;
        transaction_id: number;
    };
    query?: never;
    url: '/api/finance/v1/budgets/{budget_id}/transactions/{transaction_id}';
};

export type ApiFinanceV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiFinanceV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetError = ApiFinanceV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetErrors[keyof ApiFinanceV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetErrors];

export type ApiFinanceV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetResponses = {
    /**
     * Document created, URL follows
     */
    201: {
        [key: string]: string;
    };
};

export type ApiFinanceV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetResponse = ApiFinanceV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetResponses[keyof ApiFinanceV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetResponses];

export type ApiFinanceV1BudgetsAllGetAllBudgetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/finance/v1/budgets/all';
};

export type ApiFinanceV1BudgetsAllGetAllBudgetsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: AllBudgetsResponse;
};

export type ApiFinanceV1BudgetsAllGetAllBudgetsResponse = ApiFinanceV1BudgetsAllGetAllBudgetsResponses[keyof ApiFinanceV1BudgetsAllGetAllBudgetsResponses];

export type ApiFinanceV1BudgetsNamesGetBudgetsNamesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/finance/v1/budgets/names';
};

export type ApiFinanceV1BudgetsNamesGetBudgetsNamesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<BudgetNameResponse>;
};

export type ApiFinanceV1BudgetsNamesGetBudgetsNamesResponse = ApiFinanceV1BudgetsNamesGetBudgetsNamesResponses[keyof ApiFinanceV1BudgetsNamesGetBudgetsNamesResponses];

export type ApiFinanceV1UserTokenUpdateAccessUrlEndpointData = {
    body: TokenRequest;
    path?: never;
    query?: never;
    url: '/api/finance/v1/user/token';
};

export type ApiFinanceV1UserTokenUpdateAccessUrlEndpointErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiFinanceV1UserTokenUpdateAccessUrlEndpointError = ApiFinanceV1UserTokenUpdateAccessUrlEndpointErrors[keyof ApiFinanceV1UserTokenUpdateAccessUrlEndpointErrors];

export type ApiFinanceV1UserTokenUpdateAccessUrlEndpointResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: {
        [key: string]: string;
    };
};

export type ApiFinanceV1UserTokenUpdateAccessUrlEndpointResponse = ApiFinanceV1UserTokenUpdateAccessUrlEndpointResponses[keyof ApiFinanceV1UserTokenUpdateAccessUrlEndpointResponses];
