// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * TransactionWithBreakdownResponse
 */
export type TransactionWithBreakdownResponse = {
    id: number;
    transaction_id: string;
    amount: number;
    description?: string | null;
    payee?: string | null;
    transacted_at: string;
    is_split: boolean;
    budget_id?: number | null;
    line_items?: Array<TransactionLineItemResponse>;
};

/**
 * TransactionLineItemResponse
 */
export type TransactionLineItemResponse = {
    id: number;
    description: string;
    amount: number;
    quantity?: number | null;
    unit_price?: number | null;
    category?: string | null;
    budget_id?: number | null;
    notes?: string | null;
};

/**
 * TransactionTypeEnum
 */
export type TransactionTypeEnum = 'transfer' | 'credit_payment' | 'loan_payment';

/**
 * TransactionResponse
 */
export type TransactionResponse = {
    id: number;
    transaction_id: string;
    amount: number;
    description?: string | null;
    payee?: string | null;
    transacted_at: string;
    pending: boolean;
    is_split: boolean;
    transaction_type?: string | null;
    exclude_from_budget: boolean;
    budget?: TransactionBudget | null;
    account: TransactionAccount;
};

/**
 * AccountOrg
 */
export type AccountOrg = {
    id: number;
    domain: string;
    sfin_url: string;
    url?: string;
    name?: string;
};

/**
 * TransactionAccount
 */
export type TransactionAccount = {
    id: number;
    account_id: string;
    name: string;
    currency: string;
    balance: number;
    available_balance?: number | null;
    balance_date: string;
    possible_error: boolean;
    extra?: {
        [key: string]: unknown;
    } | null;
    updated_at: string;
    org: AccountOrg;
};

/**
 * TransactionBudget
 */
export type TransactionBudget = {
    id: number;
    name: string;
};

/**
 * TokenRequest
 */
export type TokenRequest = {
    token: string;
};

/**
 * PaginatedTransactionResponse
 */
export type PaginatedTransactionResponse = {
    transactions: Array<TransactionResponse>;
    total: number;
    page: number;
    rows_per_page: number;
};

/**
 * MessageResponse
 */
export type MessageResponse = {
    message: string;
};

/**
 * MarkTransactionTypeRequest
 */
export type MarkTransactionTypeRequest = {
    transaction_type?: TransactionTypeEnum | null;
    exclude_from_budget?: boolean;
};

/**
 * IncomeBudgetResponse
 */
export type IncomeBudgetResponse = {
    id: number;
    user_id: number;
    enable: boolean;
    deleted: boolean;
    fixed: boolean;
    expected_amount?: number | null;
    min?: number | null;
    max?: number | null;
    name: string;
    transaction_sum: number;
    amount_after_transactions: number;
    carryover: number;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    status: string;
};

/**
 * FundBudgetResponse
 */
export type FundBudgetResponse = {
    id: number;
    user_id: number;
    enable: boolean;
    deleted: boolean;
    priority?: number | null;
    increment?: number | null;
    current_amount?: number | null;
    max?: number | null;
    name: string;
    transaction_sum: number;
    amount_after_transactions: number;
    carryover: number;
};

/**
 * FlexibleBudgetResponse
 */
export type FlexibleBudgetResponse = {
    id: number;
    user_id: number;
    enable: boolean;
    deleted: boolean;
    fixed: boolean;
    expected_amount?: number | null;
    min?: number | null;
    max?: number | null;
    name: string;
    transaction_sum: number;
    amount_after_transactions: number;
    carryover: number;
};

/**
 * ExpenseBudgetResponse
 */
export type ExpenseBudgetResponse = {
    id: number;
    user_id: number;
    enable: boolean;
    deleted: boolean;
    fixed: boolean;
    expected_amount?: number | null;
    min?: number | null;
    max?: number | null;
    name: string;
    transaction_sum: number;
    amount_after_transactions: number;
    carryover: number;
};

/**
 * CreateLineItemRequest
 */
export type CreateLineItemRequest = {
    description: string;
    amount: number;
    quantity?: number | null;
    unit_price?: number | null;
    category?: string | null;
    budget_id?: number | null;
    notes?: string | null;
};

/**
 * CreateBreakdownRequest
 */
export type CreateBreakdownRequest = {
    transaction_id: number;
    line_items: Array<CreateLineItemRequest>;
};

/**
 * CopyBudgetsResponse
 */
export type CopyBudgetsResponse = {
    message: string;
    copied_budgets: CopiedBudgetCounts;
    source_month: number;
    source_year: number;
};

/**
 * CopiedBudgetCounts
 */
export type CopiedBudgetCounts = {
    income: number;
    expense: number;
    flexible: number;
    fund: number;
};

/**
 * CopyBudgetsRequest
 */
export type CopyBudgetsRequest = {
    target_month: number;
    target_year: number;
    source_month?: number | null;
    source_year?: number | null;
};

/**
 * BudgetRequest
 */
export type BudgetRequest = {
    name: string;
    fixed?: boolean;
    flexible?: boolean;
    budget_type: string;
    expected_amount?: number | null;
    min?: number | null;
    max?: number | null;
    priority?: number | null;
    increment?: number | null;
    current_amount?: number | null;
    month: number;
    year: number;
};

/**
 * BudgetNameResponse
 */
export type BudgetNameResponse = {
    name: string;
    id: number;
};

/**
 * AllBudgetsResponse
 */
export type AllBudgetsResponse = {
    incomes?: Array<IncomeBudgetResponse>;
    expenses?: Array<ExpenseBudgetResponse>;
    flexibles?: Array<FlexibleBudgetResponse>;
    funds?: Array<FundBudgetResponse>;
};

export type ApiV1UserTokenUpdateAccessUrlEndpointData = {
    body: TokenRequest;
    path?: never;
    query?: never;
    url: '/api/finance/v1/user/token';
};

export type ApiV1UserTokenUpdateAccessUrlEndpointErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiV1UserTokenUpdateAccessUrlEndpointError = ApiV1UserTokenUpdateAccessUrlEndpointErrors[keyof ApiV1UserTokenUpdateAccessUrlEndpointErrors];

export type ApiV1UserTokenUpdateAccessUrlEndpointResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: MessageResponse;
};

export type ApiV1UserTokenUpdateAccessUrlEndpointResponse = ApiV1UserTokenUpdateAccessUrlEndpointResponses[keyof ApiV1UserTokenUpdateAccessUrlEndpointResponses];

export type ApiV1BudgetsCreateCreateBudgetData = {
    body: BudgetRequest;
    path?: never;
    query?: never;
    url: '/api/finance/v1/budgets/create';
};

export type ApiV1BudgetsCreateCreateBudgetErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiV1BudgetsCreateCreateBudgetError = ApiV1BudgetsCreateCreateBudgetErrors[keyof ApiV1BudgetsCreateCreateBudgetErrors];

export type ApiV1BudgetsCreateCreateBudgetResponses = {
    /**
     * Document created, URL follows
     */
    201: MessageResponse;
};

export type ApiV1BudgetsCreateCreateBudgetResponse = ApiV1BudgetsCreateCreateBudgetResponses[keyof ApiV1BudgetsCreateCreateBudgetResponses];

export type ApiV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetData = {
    body?: never;
    path: {
        budget_id: number;
        transaction_id: number;
    };
    query?: never;
    url: '/api/finance/v1/budgets/{budget_id}/transactions/{transaction_id}';
};

export type ApiV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetError = ApiV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetErrors[keyof ApiV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetErrors];

export type ApiV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: MessageResponse;
};

export type ApiV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetResponse = ApiV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetResponses[keyof ApiV1BudgetsBudgetIdTransactionsTransactionIdAddTransactionToBudgetResponses];

export type ApiV1BudgetsAllGetAllBudgetsData = {
    body?: never;
    path?: never;
    query?: {
        month?: number | null;
        year?: number | null;
    };
    url: '/api/finance/v1/budgets/all';
};

export type ApiV1BudgetsAllGetAllBudgetsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiV1BudgetsAllGetAllBudgetsError = ApiV1BudgetsAllGetAllBudgetsErrors[keyof ApiV1BudgetsAllGetAllBudgetsErrors];

export type ApiV1BudgetsAllGetAllBudgetsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: AllBudgetsResponse;
};

export type ApiV1BudgetsAllGetAllBudgetsResponse = ApiV1BudgetsAllGetAllBudgetsResponses[keyof ApiV1BudgetsAllGetAllBudgetsResponses];

export type ApiV1BudgetsNamesGetBudgetsNamesData = {
    body?: never;
    path?: never;
    query?: {
        month?: number | null;
        year?: number | null;
    };
    url: '/api/finance/v1/budgets/names';
};

export type ApiV1BudgetsNamesGetBudgetsNamesErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiV1BudgetsNamesGetBudgetsNamesError = ApiV1BudgetsNamesGetBudgetsNamesErrors[keyof ApiV1BudgetsNamesGetBudgetsNamesErrors];

export type ApiV1BudgetsNamesGetBudgetsNamesResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: Array<BudgetNameResponse>;
};

export type ApiV1BudgetsNamesGetBudgetsNamesResponse = ApiV1BudgetsNamesGetBudgetsNamesResponses[keyof ApiV1BudgetsNamesGetBudgetsNamesResponses];

export type ApiV1BudgetsCopyFromPreviousCopyBudgetsFromPreviousData = {
    body: CopyBudgetsRequest;
    path?: never;
    query?: never;
    url: '/api/finance/v1/budgets/copy-from-previous';
};

export type ApiV1BudgetsCopyFromPreviousCopyBudgetsFromPreviousErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiV1BudgetsCopyFromPreviousCopyBudgetsFromPreviousError = ApiV1BudgetsCopyFromPreviousCopyBudgetsFromPreviousErrors[keyof ApiV1BudgetsCopyFromPreviousCopyBudgetsFromPreviousErrors];

export type ApiV1BudgetsCopyFromPreviousCopyBudgetsFromPreviousResponses = {
    /**
     * Document created, URL follows
     */
    201: CopyBudgetsResponse;
};

export type ApiV1BudgetsCopyFromPreviousCopyBudgetsFromPreviousResponse = ApiV1BudgetsCopyFromPreviousCopyBudgetsFromPreviousResponses[keyof ApiV1BudgetsCopyFromPreviousCopyBudgetsFromPreviousResponses];

export type ApiV1TransactionsGetTransactionsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        descending?: boolean;
        sort_by?: string;
        rows_per_page?: number;
        include_excluded?: boolean;
        transaction_type?: number | null;
        month?: number | null;
        year?: number | null;
    };
    url: '/api/finance/v1/transactions';
};

export type ApiV1TransactionsGetTransactionsErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiV1TransactionsGetTransactionsError = ApiV1TransactionsGetTransactionsErrors[keyof ApiV1TransactionsGetTransactionsErrors];

export type ApiV1TransactionsGetTransactionsResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: PaginatedTransactionResponse;
};

export type ApiV1TransactionsGetTransactionsResponse = ApiV1TransactionsGetTransactionsResponses[keyof ApiV1TransactionsGetTransactionsResponses];

export type ApiV1TransactionsUpdateUpdateTransactionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/finance/v1/transactions/update';
};

export type ApiV1TransactionsUpdateUpdateTransactionsResponses = {
    /**
     * Document created, URL follows
     */
    201: MessageResponse;
};

export type ApiV1TransactionsUpdateUpdateTransactionsResponse = ApiV1TransactionsUpdateUpdateTransactionsResponses[keyof ApiV1TransactionsUpdateUpdateTransactionsResponses];

export type ApiV1TransactionsTransactionIdBreakdownGetBreakdownData = {
    body?: never;
    path: {
        transaction_id: number;
    };
    query?: never;
    url: '/api/finance/v1/transactions/{transaction_id}/breakdown';
};

export type ApiV1TransactionsTransactionIdBreakdownGetBreakdownErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiV1TransactionsTransactionIdBreakdownGetBreakdownError = ApiV1TransactionsTransactionIdBreakdownGetBreakdownErrors[keyof ApiV1TransactionsTransactionIdBreakdownGetBreakdownErrors];

export type ApiV1TransactionsTransactionIdBreakdownGetBreakdownResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: TransactionWithBreakdownResponse;
};

export type ApiV1TransactionsTransactionIdBreakdownGetBreakdownResponse = ApiV1TransactionsTransactionIdBreakdownGetBreakdownResponses[keyof ApiV1TransactionsTransactionIdBreakdownGetBreakdownResponses];

export type ApiV1TransactionsTransactionIdBreakdownCreateBreakdownData = {
    body: CreateBreakdownRequest;
    path: {
        transaction_id: number;
    };
    query?: never;
    url: '/api/finance/v1/transactions/{transaction_id}/breakdown';
};

export type ApiV1TransactionsTransactionIdBreakdownCreateBreakdownErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiV1TransactionsTransactionIdBreakdownCreateBreakdownError = ApiV1TransactionsTransactionIdBreakdownCreateBreakdownErrors[keyof ApiV1TransactionsTransactionIdBreakdownCreateBreakdownErrors];

export type ApiV1TransactionsTransactionIdBreakdownCreateBreakdownResponses = {
    /**
     * Document created, URL follows
     */
    201: TransactionWithBreakdownResponse;
};

export type ApiV1TransactionsTransactionIdBreakdownCreateBreakdownResponse = ApiV1TransactionsTransactionIdBreakdownCreateBreakdownResponses[keyof ApiV1TransactionsTransactionIdBreakdownCreateBreakdownResponses];

export type ApiV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointData = {
    body?: never;
    path: {
        line_item_id: number;
    };
    query?: never;
    url: '/api/finance/v1/transactions/line-items/{line_item_id}';
};

export type ApiV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointError = ApiV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointErrors[keyof ApiV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointErrors];

export type ApiV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: MessageResponse;
};

export type ApiV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointResponse = ApiV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointResponses[keyof ApiV1TransactionsLineItemsLineItemIdDeleteLineItemEndpointResponses];

export type ApiV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointData = {
    body: CreateLineItemRequest;
    path: {
        line_item_id: number;
    };
    query?: never;
    url: '/api/finance/v1/transactions/line-items/{line_item_id}';
};

export type ApiV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointError = ApiV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointErrors[keyof ApiV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointErrors];

export type ApiV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: TransactionLineItemResponse;
};

export type ApiV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointResponse = ApiV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointResponses[keyof ApiV1TransactionsLineItemsLineItemIdUpdateLineItemEndpointResponses];

export type ApiV1TransactionsTransactionIdTypeMarkTransactionTypeEndpointData = {
    body: MarkTransactionTypeRequest;
    path: {
        transaction_id: number;
    };
    query?: never;
    url: '/api/finance/v1/transactions/{transaction_id}/type';
};

export type ApiV1TransactionsTransactionIdTypeMarkTransactionTypeEndpointErrors = {
    /**
     * Validation Exception
     */
    400: {
        status_code: number;
        detail: string;
        extra?: null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
};

export type ApiV1TransactionsTransactionIdTypeMarkTransactionTypeEndpointError = ApiV1TransactionsTransactionIdTypeMarkTransactionTypeEndpointErrors[keyof ApiV1TransactionsTransactionIdTypeMarkTransactionTypeEndpointErrors];

export type ApiV1TransactionsTransactionIdTypeMarkTransactionTypeEndpointResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: TransactionResponse;
};

export type ApiV1TransactionsTransactionIdTypeMarkTransactionTypeEndpointResponse = ApiV1TransactionsTransactionIdTypeMarkTransactionTypeEndpointResponses[keyof ApiV1TransactionsTransactionIdTypeMarkTransactionTypeEndpointResponses];

export type ApiV1HealthHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/finance/v1/health';
};

export type ApiV1HealthHealthCheckResponses = {
    /**
     * Request fulfilled, document follows
     */
    200: HealthResponse;
};

export type ApiV1HealthHealthCheckResponse = ApiV1HealthHealthCheckResponses[keyof ApiV1HealthHealthCheckResponses];
