import type { TransactionResponse } from 'src/api'

export const transactionTableColumns = [
  {
    name: 'transacted_at',
    label: 'Date',
    align: 'center' as const,
    field: 'transacted_at',
    sortable: true,
    style: 'width: 90px',
  },
  {
    name: 'description',
    label: 'Description',
    align: 'left' as const,
    field: 'description',
    sortable: true,
    style: 'max-width: 200px',
    classes: 'cell-ellipsis',
  },
  {
    name: 'payee',
    label: 'Payee',
    align: 'left' as const,
    field: 'payee',
    sortable: true,
    style: 'max-width: 140px',
    classes: 'cell-ellipsis',
  },
  {
    name: 'amount',
    label: 'Amount',
    align: 'right' as const,
    field: 'amount',
    sortable: true,
    format: (val: number) => `$${val.toFixed(2)}`,
    style: 'width: 90px',
  },
  {
    name: 'account_name',
    label: 'Account',
    align: 'left' as const,
    field: (row: TransactionResponse) => row.account?.name || 'N/A',
    sortable: true,
    style: 'max-width: 130px',
    classes: 'cell-ellipsis',
  },
  {
    name: 'org_name',
    label: 'Org',
    align: 'left' as const,
    field: (row: TransactionResponse) => row.account?.org?.name || 'N/A',
    sortable: false,
    style: 'max-width: 120px',
    classes: 'cell-ellipsis',
  },
  {
    name: 'pending',
    label: 'Status',
    align: 'center' as const,
    field: 'pending',
    sortable: true,
    style: 'width: 70px',
  },
  {
    name: 'budget_name',
    label: 'Budget',
    align: 'center' as const,
    field: 'budget_name',
    sortable: true,
    style: 'max-width: 150px',
  },
  {
    name: 'actions',
    label: '',
    align: 'center' as const,
    field: 'actions',
    sortable: false,
    style: 'width: 100px',
  },
]
