"""add_transaction_rules

Revision ID: 1b2e8a826404
Revises: d95aa97b1549
Create Date: 2025-12-13 19:15:44.266810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2e8a826404'
down_revision: Union[str, None] = 'd95aa97b1549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('target_budget_id', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_budget_id'], ['budget.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_rule_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_rule_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_apply_rules', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('auto_apply_rules')

    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_rule_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_rule_id'))

    op.drop_table('transaction_rule')
    # ### end Alembic commands ###
