"""add skip transaction table

Revision ID: 1f337d253530
Revises: 339b72676a0e
Create Date: 2025-10-21 20:11:57.204596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f337d253530'
down_revision: Union[str, None] = '339b72676a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simplefin_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('exclude_from_budget', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simplefin_transaction', schema=None) as batch_op:
        batch_op.drop_column('exclude_from_budget')
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###
