"""implement fund masters

Revision ID: d95aa97b1549
Revises: 1f337d253530
Create Date: 2025-10-31 06:24:19.017852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95aa97b1549'
down_revision: Union[str, None] = '1f337d253530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_masters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fund', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month_amount', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False))
        batch_op.add_column(sa.Column('master_fund_id', sa.Integer(), nullable=False))
        batch_op.alter_column('increment',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
        batch_op.alter_column('max',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'fund_masters', ['master_fund_id'], ['id'])
        batch_op.drop_column('current_amount')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fund', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('max',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('increment',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('master_fund_id')
        batch_op.drop_column('month_amount')

    op.drop_table('fund_masters')
    # ### end Alembic commands ###
