"""add transaction type marking to rules

Revision ID: ffc25ee1af60
Revises: 1b2e8a826404
Create Date: 2026-03-15 03:58:40.447678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc25ee1af60'
down_revision: Union[str, None] = '1b2e8a826404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_transaction_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('target_exclude_from_budget', sa.Boolean(), server_default='false', nullable=False))
        batch_op.alter_column('target_budget_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_rule', schema=None) as batch_op:
        batch_op.alter_column('target_budget_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('target_exclude_from_budget')
        batch_op.drop_column('target_transaction_type')

    # ### end Alembic commands ###
